apiVersion: v1
kind: Secret
metadata:
  name: selenium-integration-secret
type: Opaque
data:
  sqs.aws.region: ZXUtY2VudHJhbC0x
  sqs.aws.credentials.access-key: QUtJQTJWTFlDSkRBRTZaQ1NYNU8K
  sqs.aws.credentials.secret-key: bnM2RDlUb0NuQTVwNmRWRTUzR1JQcEViK1ZsN255WGdMTjVRRFRIWgo=